on:
  workflow_dispatch:
  release:
    types: [ published ]
jobs:
  build:
    runs-on: ubuntu-24.04-arm
    name: Build and push genai/messages-service image
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/arm64
          context: ./
          push: true
          tags: ${{ secrets.REGISTRY }}/genai/messages-service:latest
